-- 1. Create Artworks Table
CREATE TABLE artworks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  src TEXT NOT NULL,
  title TEXT NOT NULL,
  medium TEXT,
  description TEXT,
  featured BOOLEAN DEFAULT false,
  order_idx INTEGER DEFAULT 0
);

-- 2. Create About Table
CREATE TABLE about (
  id INTEGER PRIMARY KEY DEFAULT 1,
  bio TEXT,
  quote TEXT,
  para2 TEXT,
  para3 TEXT,
  para4 TEXT,
  para5 TEXT
);

-- 3. Create Exhibition Table
CREATE TABLE exhibition (
  id INTEGER PRIMARY KEY DEFAULT 1,
  enabled BOOLEAN DEFAULT true,
  label TEXT,
  title TEXT,
  subtitle TEXT,
  venue TEXT,
  city TEXT,
  dates TEXT,
  description TEXT
);

-- 4. Create Site Settings Table (for the Hero Quote)
CREATE TABLE site_settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  hero_quote TEXT
);

-- 5. Insert Default Data into About, Exhibition, and Site Settings
INSERT INTO about (id, bio, quote, para2, para3, para4, para5) VALUES (
  1,
  'Yunus Khimani is a distinguished Indian artist whose work traverses the boundaries between figuration and expression. Born and raised in India, he developed an early fascination with the human form and the emotional narratives it carries. His artistic journey has been shaped by rigorous academic training and decades of professional practice spanning painting, education, and museum curation.',
  '"My work is an exploration of the human condition — each figure, each line, each gesture is a meditation on what it means to be alive, to feel, to fear, and to hope."',
  'Khimani earned his Bachelor of Fine Arts (BFA) from the prestigious Faculty of Fine Arts, Maharaja Sayajirao University of Baroda (1981), one of India''s most respected institutions for visual arts. This foundational training in the Baroda school tradition — known for its emphasis on figuration, narrative, and social commentary — deeply influenced his artistic vocabulary.',
  'His paintings are characterized by intricate cross-hatching, bold earth tones of burnt sienna, deep crimson, and raw umber, layered over expansive canvases. The figures in his works seem to emerge from and dissolve into their surroundings, creating a powerful tension between presence and absence, solidity and fragility.',
  'Beyond his studio practice, Khimani has made significant contributions to India''s cultural landscape. He served as Director of the City Palace Museum, Jaipur from 2010 to 2018, overseeing one of India''s most important heritage collections. He has also served as Dean and Associate Professor at the Indian Institute of Crafts and Design (IICD), Jaipur, shaping the next generation of visual artists and designers.',
  'In 1996, he was awarded the Junior Fellowship by the Ministry of Culture, Government of India — a recognition of his outstanding contributions to the visual arts. His work has been exhibited extensively across India, with solo and group shows at prestigious galleries.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO exhibition (id, enabled, label, title, subtitle, venue, city, dates, description) VALUES (
  1,
  true,
  'Current Exhibition',
  '"I FEAR........"',
  'A Solo Exhibition of Paintings',
  'Jehangir Art Gallery',
  'Mumbai',
  '30th December 2025 — 5th January 2026',
  'An intimate exploration of fear, vulnerability, and the human condition through large-scale figurative works in oil, acrylic, and mixed media.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO site_settings (id, hero_quote) VALUES (
  1,
  '"Art is the mirror of the soul — each line I draw is a conversation between my inner world and the canvas, a silent dialogue that speaks louder than words."'
) ON CONFLICT (id) DO NOTHING;

-- 6. Important: Enable Row Level Security (RLS) but allow public read/write for now
-- Note: For a production app, you would lock down write access to authenticated users only.
-- Because this is a simple portfolio, we'll allow public access.
ALTER TABLE artworks ENABLE ROW LEVEL SECURITY;
ALTER TABLE about ENABLE ROW LEVEL SECURITY;
ALTER TABLE exhibition ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on artworks" ON artworks FOR SELECT USING (true);
CREATE POLICY "Allow public all access on artworks" ON artworks FOR ALL USING (true);

CREATE POLICY "Allow public read access on about" ON about FOR SELECT USING (true);
CREATE POLICY "Allow public all access on about" ON about FOR ALL USING (true);

CREATE POLICY "Allow public read access on exhibition" ON exhibition FOR SELECT USING (true);
CREATE POLICY "Allow public all access on exhibition" ON exhibition FOR ALL USING (true);

CREATE POLICY "Allow public read access on site_settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Allow public all access on site_settings" ON site_settings FOR ALL USING (true);
